version: "3"

services:
  phantom_frontend:
    container_name: phantom_frontend
    image: sezeranojchrisostome/phantom:latest
    expose:
      - 8080
    ports:
      - "8080:8080"
  phantom_database:
    container_name: phantom_database
    restart: always
    image: 'postgres:14'
    ports:
      - "7000"
    expose:
      - 7000
    environment:
      - POSTGRES_PASSWORD=test123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dev_db
      - PGPORT=7000
    volumes:
      - pgdata1:/var/lib/postgress/data
  redis_server:
    container_name: redis_server
    image: 'redis:alpine'
    build:
      context: .
    expose:
      - 6379
    ports:
      - "6379:6379"    
  phantom_backend:
    container_name: phantom_backend
    build:
      context: .
    expose:
      - 5000
    environment:
      - DEV_DATABASE_URL=postgres://postgres:test123@phantom_database:7000/dev_db
      - ENVIRONMENT=development
    ports:
      - "5000:5000"
    depends_on:
      - phantom_database
  
volumes:
  pgdata1: {}